create table if not exists public.ecensus_chat_logs (
  id bigint generated by default as identity primary key,
  diagnostic_id text,
  created_at timestamptz not null default now(),
  question text not null,
  answer text not null,
  api_key_index integer,
  model text,
  candidate_count integer default 0
);

create index if not exists ecensus_chat_logs_created_at_idx
  on public.ecensus_chat_logs (created_at desc);

create index if not exists ecensus_chat_logs_diagnostic_id_idx
  on public.ecensus_chat_logs (diagnostic_id);
